version: '3.8'

services:
  torserve:
    build: .
    image: pwa-torserve:dev
    container_name: torserve-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DOWNLOAD_PATH=/downloads
      - DB_PATH=/app/data/db.json
    volumes:
      # Local Mac Mapping
      - ./downloads:/downloads
      # Persistence for DB
      - ./data:/app/data
